### ISSUE TITLE
Gain access to Spock and ALCF testbeds

### ISSUE THREAD

**Issue by mturilli** [BNL-C3D/CANDLE#3] opened 2021-10-25 22:58 UTC
Please confirm here whether we gained access to the two machines. We can add details on how to gain that access here if useful.

**Comment by vrpascuzzi** [comment] 2021-10-29 21:43
I'm all set on {A,O}LCF -- confirmed login to Spock and JLSE/Arcticus.

P.S. Getting access to these resources is practically a full-time job.

**Comment by mturilli** [comment] 2021-11-01 18:30
Coordinate with the RTC development team to access ans support these machines. Deadline is 15 days, so we should try to do this ASAP.

**Comment by vrpascuzzi** [comment] 2021-11-18 22:53
tl;dr;
Successfully ran `00_getting_started.py` on Iris and Arcticus.

Details:
Created SSH tunnel from login node to external MongoDB:
```
ssh -f -n -L $(host `hostname` | awk '{print $NF}'):27017:95.217.193.116:27017 $(host `hostname`) sleep 7200
```
(`sleep` call is nice to keep the current session and put `ssh` into the background.)

Modified `bootstrap_0.sh` to:
1) handle ANL/JLSE nodes (e.g., no `ifconfig` on login or compute nodes); and
2) set `RP_BS_TUNNEL` appropriately, as per SSH tunnel above.

Did notice the following in `bootstrap_0.out`:

```
<...>
172 1637260733.7813,bootstrap_0_ok,bootstrap_0,MainThread,pilot.0000,PMGR_ACTIVE_PENDING,
173 ......1637260751.7970,killme,bootstrap_0,MainThread,pilot.0000,PMGR_ACTIVE_PENDING,2021-11-18 18:39:11.795
174 1637260751.8020,sigterm,bootstrap_0,MainThread,pilot.0000,PMGR_ACTIVE_PENDING,2021-11-18 18:39:11.800
175 send SIGTERM to 20051 (19679)
176 COND start 'kill -0  20051' (I: 1 T: 30)
177 ./bootstrap_0.sh: line 310: 20051 Terminated              ./bootstrap_2.sh 'agent.0' > agent.0.bootstrap_2.out 2> agent.0.bootstrap_    2.err
178 ./bootstrap_0.sh: line 323: kill: (20051) - No such process
179 COND failed (1)
180 agent 20051 is final
181 agent 20051 is final (143)
182 1637260752.8124,agent_final,bootstrap_0,MainThread,pilot.0000,PMGR_ACTIVE_PENDING,20051:143 2021-11-18 18:39:12.810
<...>
```
but this looks harmless (correct me if I'm wrong).

**Comment by andre-merzky** [comment] 2021-11-22 23:19
Update on spock: basically the same situation as described by @vrpascuzzi on Arcticus: need to establish an ssh tunnel manually to get things to work:

```sh
ssh -f -n -L 0.0.0.0:27017:95.217.193.116:27017 login2.spock.olcf.ornl.gov sleep 7200
export RADICAL_PILOT_DBURL=mongodb://user:pass@login2.spock.olcf.ornl.gov:27017/am
```

I'll open a ticket to inquire about MongoDB hosting on-site.

**Comment by darkwhite29** [comment] 2021-12-06 18:21
Hi all,
I am using the manual tunnel setting up procedure as above (tried either Vince or Andre's solution) on Spock, but got the following error:
```
bind [0.0.0.0]:27017: Address already in use
channel_setup_fwd_listener_tcpip: cannot listen to port: 27017
Could not request local forwarding.
```
I guess it is because Andre is already using this port?

**Comment by vrpascuzzi** [comment] 2021-12-06 18:22
Unless he's currently using it, and on the same login node, I'm not sure how this would affect.

What is the full command you're using?

**Comment by darkwhite29** [comment] 2021-12-06 18:41
Yes, we are on the same login node (`login2.spock`).

I tried the one you listed: `ssh -f -n -L $(host `hostname` | awk '{print $NF}'):27017:95.217.193.116:27017 $(host `hostname`) sleep 7200`

and the one he listed: `ssh -f -n -L 0.0.0.0:27017:95.217.193.116:27017 login2.spock.olcf.ornl.gov sleep 7200`

Both gave me the same error message.

**Comment by vrpascuzzi** [comment] 2021-12-06 18:46
Can you try a different login node?

**Comment by darkwhite29** [comment] 2021-12-06 19:36
Hi @mturilli, I am using my old username and password (assume my password did not change) on the RabbitMQ server. When I tried to run an EnTK code, I got the following authentication error:
`radical.entk.exceptions.EnTKError: (403, 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.')`
I did some research online and found this: https://stackoverflow.com/questions/26811924/spring-amqp-rabbitmq-3-3-5-access-refused-login-was-refused-using-authentica
Do you think you need to reset my password? Thanks!

**Comment by mturilli** [comment] 2021-12-06 19:44
Hi @darkwhite29 , moved this to a private channel.

**Comment by vrpascuzzi** [comment] 2021-12-13 15:43
Think we can close this one.

**Closed** 2021-12-13 22:24 UTC
